ui = shinyUI({fluidPage(
  
  dashboardPage(
    dashboardHeader(title = 'Hurd Laboratory', 
                    tags$li(class = 'dropdown', 
                            style = 'width: 1550px; height: 0px; padding: 0px')
    ), #dashboard header end
    
    dashboardSidebar(
      
      width = 273.5,
      
      sidebarMenuOutput("Semi_collapsible_sidebar"),
      fluidRow(
        align = "center",
        br(),
        tags$a(href = 'https://www.mountsinai.org', style = 'height: 0px; padding: 0px'), # this is where you would put your own image from the folder "www"
        tags$img(src = 'mountsinai.png', style = 'height: 100px; width: 200px'), 
        br(),
        br(),
        br(),
        "The following dropdown menu for",
        br(),
        "'Y Variable' toggles the plots on", 
        br(),
        "the 'Main Plot', 'Subjects', and",
        br(),
        "'Univariate Plots' tabs.",
        br(),
        selectInput("y", "Y Variable", 
                    choices = c("active", "inactive","percent.active", "percent.inactive", "reward", "activity"),
                    multiple = FALSE,
                    selected = "active"),
        #downloadButton("downloadplot","Download Plot"), 
        br(),
        radioButtons(inputId = "filetype",
                     label = "Select filetype:",
                     choices = c("csv", "tsv", "xlsx"),
                     selected = "csv"),
        HTML("Select filetype, then 'Download Data'"),
        br(),
        downloadButton("downloaddata", "Download Data"))),
    
    
    dashboardBody(
      style = "overflow-x: scroll",
      fluidRow(
        align = "center",
        div(id = "loading-content", h2("Loading...")),
        mainPanel(
          style = "width: 100%",
          tabsetPanel(type = "tabs",
                      tabPanel(tags$b("Research Design"),
                               br(),
                               box(width=12,
                                   title="Research Goal", solidHeader = TRUE,
                                   "The following experiment was designed to determine the mechanisms through which cocaine and opioid self-administration causes persistent alterations in the protein profile of synapses within the nucleus accumbens, a brain region critical for drug-seeking."),
                               box(width=12,
                                   title="Surgery", solidHeader = TRUE,
                                   "Thirty male Long-Evans rats underwent jugular vein catheterization surgery.", 
                                   br(),
                                   "After surgery, animals were given a 3-day recovery period, in which they were treated with 0.1 ml ampicillin and 0.03 ml carprofen s.c. (5mg/kg).",
                                   br(),
                                   "Catheter patency was affirmed through observable loss of muscle tone with administration of brevital. Animals that did not show catheter patency were excluded from the experiment.",
                                   br(),
                                   "Catheters were flushed daily before and after every self-administration session with 0.1 ml of heparinized (30 IU/ml) saline to prevent clotting for the duration of the experiment."),
                               box(width=12,
                                   title="Self-Administration", solidHeader = TRUE,
                                   "For the rest of the experiment, animals were food restricted (18g chow/day).",
                                   br(),
                                   "There were 8 animals assigned to each self-administration group: heroin, cocaine, and saline.",
                                   br(),
                                   "Self-administration training occurred in operant chambers (Med Associates).",
                                   br(),
                                   "Animals were allowed 6-hour daily access to heroin (0.03mg/kg/i.v.), cocaine (0.8mg/kg/i.v.) or saline under a fixed ratio-1 (FR-1) reinforcement schedule.",
                                   br(),
                                   "Pressing the active lever triggered a 5-second drug infusion with a conditioned cue light stimulus followed by a 20-second timeout period.",
                                   br(),
                                   "Pressing the inactive lever had no effect.",
                                   br(),
                                   "After 12-15 sessions of self-administration, animals underwent 30 days of forced abstinence. Thereafter, animals were euthanized, and their brains were extracted for proteomic analysis of the nucleus accumbens.")),
                      tabPanel(tags$b("Master Data"),
                               br(),
                               DT::dataTableOutput("master.data"), style = "height: auto !important; overflow-y: scroll; overflow-x: scroll;"),
                      tabPanel(tags$b("Main Plot"),
                               br(),
                               box(width=12,
                                   title= "Y Variable by Sessions", solidHeader = TRUE, 
                                   plotOutput("plot") %>% withSpinner(color="#0dc5c1")),
                               box(width=12,
                                   title="Session Input", solidHeader=TRUE,
                                   sliderInput("session", "Sessions", 
                                               min(FR_data$session), max(FR_data$session),
                                               value = c(1, 40),
                                               step=1)),
                               box(width=12,
                                   title= "Y Variable Data Summary by Sessions", solidHeader=TRUE,
                                   DT::dataTableOutput("table"), style = "height: auto !important; overflow-y: scroll; overflow-x: scroll;")),
                      tabPanel(tags$b("Subjects"), 
                               br(),
                               box(width=12,
                                   title="Individual subjects from cocaine group",
                                   plotOutput("plot2", height="1000px") %>% withSpinner(color="#0dc5c1")),
                               box(width=12,
                                   title="Individual subjects from heroin group",
                                   plotOutput("plot3", height="1000px") %>% withSpinner(color="#0dc5c1")),
                               box(width=12,
                                   title="Individual subjects from saline group",
                                   plotOutput("plot7", height="1000px") %>% withSpinner(color="#0dc5c1"))),
                      tabPanel(tags$b("Univariate Plots"),
                               br(),
                               fluidRow(box(width=12,
                                            title="Observation and Exclusion", 
                                            "*Hover on a data point to see a subject's self-administration performance.",
                                            br(),
                                            "*Click on a data point to exclude a subject from the boxplot.",
                                            br(),
                                            "*Brush (i.e. click and drag) over multiple data points and click the 'Exclude Brush Points' button to exclude multiple data points.",
                                            br(),
                                            "Exclusions are reflected in the analysis tabs.",
                                            br(),
                                            "When a subject's inactive/active lever press is excluded, the entire session data are excluded.",
                                            br(),
                                            "As a result, a subject's 'last 3 sessions' are always re-calibrated.",
                                            br(),
                                            br(),
                                            actionButton("exclude_toggle", "Exclude Brushed Points"),
                                            actionButton("exclude_reset", "Reset Graphs"))),
                               box(width=12,
                                   title="Box plots by session for cocaine group",
                                   plotOutput("plot4", click = "plot_click1", brush = brushOpts(id = "plot_brush1"), hover = hoverOpts("plot_hover1"))),
                               box(width=12,
                                   title="HoverPoint Info for cocaine group",
                                   verbatimTextOutput("hover_info1")),
                               box(width=12,
                                   title="Box plots by session for heroin group",
                                   plotOutput("plot5", click = "plot_click2", brush = brushOpts(id = "plot_brush2"), hover = hoverOpts("plot_hover2"))),
                               box(width=12,
                                   title="HoverPoint Infor for heroin group",
                                   verbatimTextOutput("hover_info2")),
                               box(width=12,
                                   title="Box plots by session for saline group",
                                   plotOutput("plot6", click = "plot_click3", brush = brushOpts(id = "plot_brush3"), hover = hoverOpts("plot_hover3"))),
                               box(width=12,
                                   title="HoverPoint Infor for saline group",
                                   verbatimTextOutput("hover_info3"))),
                      tabPanel(tags$b("Analysis of Variance"),
                               br(),
                               box(width=12,
                                   title="Information",
                                   "*These are repeated measures of variance analysis using a linear mixed-effects model (LMM) across all sessions.",
                                   br(),
                                   "Individual subjects nested within treatment is annotated as a random effect.",
                                   br(),
                                   "An ANOVA using LMM can be conducted when the data have met two primary assumptions:",
                                   br(),
                                   "1)The assumption of normality - in which you can check with the univariate plots.",
                                   br(),
                                   "2)The assumption of homoscedasticity - in which you can check with the residual plots."),
                               box(width=6,
                                   title="Q-Q Plot",
                                   plotOutput("residualplot1") %>% withSpinner(color="#0dc5c1")),
                               box(width=6,
                                   title="Residuals by Group",
                                   plotOutput("residualplot2") %>% withSpinner(color="#0dc5c1")),
                               box(width=6,
                                   title="Analysis of Deviance Table (Type II Wald chisquare tests)",
                                   verbatimTextOutput("stats_wald2")),
                               box(width=6,
                                   title="Analysis of Deviance Table (Type III Wald chisquare tests)",
                                   verbatimTextOutput("stats_wald3")),
                               box(width=12,
                                   title="Plot of Estimated Means",
                                   plotOutput("int_plot") %>% withSpinner(color="#0dc5c1")),
                               box(width=6,
                                   title="TukeyHSD PostHoc Analysis",
                                   verbatimTextOutput("stats_tukey")),
                               box(width=6,
                                   title="Interaction Analysis",
                                   verbatimTextOutput("contrasts1"))),
                      
                      tabPanel(tags$b("Last 3 sessions Analysis"), 
                               br(),
                               box(width=12,
                                   title="Information",
                                   "*These are repeated measures of variance analysis using a linear mixed-effects model (LMM) across the last 3 sessions.",
                                   br(),
                                   "Individual subjects nested within treatment is annotated as a random effect.",
                                   br(),
                                   "An ANOVA using LMM can be conducted when the data have met two primary assumptions:",
                                   br(),
                                   "1)The assumption of normality - in which you can check with the univariate plots.",
                                   br(),
                                   "2)The assumption of homoscedasticity - in which you can check with the residual plots."),
                               box(width=6,
                                   title="Q-Q Plot",
                                   plotOutput("residualplot3") %>% withSpinner(color="#0dc5c1")),
                               box(width=6,
                                   title="Residuals by Group",
                                   plotOutput("residualplot4") %>% withSpinner(color="#0dc5c1")),
                               box(width=6,
                                   title="Analysis of Deviance Table (Type II Wald chisquare tests)",
                                   verbatimTextOutput("last3sessions_anova2")),
                               box(width=6,
                                   title="Analysis of Deviance Table (Type III Wald chisquare tests)",
                                   verbatimTextOutput("last3sessions_anova3")),
                               box(width=12,
                                   title="Plot of Estimated Means",
                                   plotOutput("int_plot2") %>% withSpinner(color="#0dc5c1")),
                               box(width=6,
                                   title="TukeyHSD PostHoc Analysis",
                                   verbatimTextOutput("stats_tukey2")),
                               box(width=6,
                                   title="Interaction Analysis",
                                   verbatimTextOutput("contrasts2")))
                      
          ) #tabsetpanel end
        ) #main panel end
        
      ), #fluid row end
      
      tags$head(tags$style(HTML('.wrapper {height: auto !important; position: relative;}'))),
      #tags$head(class = "navbar", tags$a(href = "http://labs.neuroscience.mssm.edu/project/hurd-lab/", tags$img(src = 'header.png', style = "height: 200px; width: 25%;"))),
      tags$style(HTML(".skin-blue .main-header .navbar {border-width: thin; border-bottom-style: solid;  border-right-style: solid; 
                    border-color: #00002D; background-color: #06ABEB; color: white; border-left-style: solid;}")),
      tags$style(HTML(".skin-blue .main-header .navbar .sidebar-toggle {background-color: #06ABEB; color:black; border-right-style: solid; border-width: thin;}")),
      tags$style(HTML(".skin-blue .main-header .navbar .sidebar-toggle:hover {background-color: white; color:black;}")),
      tags$style(HTML(".skin-blue .main-header .logo {background-color: #06ABEB; color:black;}")),
      tags$style(HTML(".skin-blue > .main-header > logo:hover {background-color: #06ABEB; color:black;}")),
      tags$style(HTML(".irs-bar {background-color: #06ABEB;}")),
      tags$style(HTML(".skin-blue .main-sidebar {background-color: #00002D; border-color: #00002D; border-style: solid; border-width: thin;}")),
      tags$style(HTML(".tabbable > .nav > li > a {background-color: #DC298D; color:white; border-color: #212070; border-style: solid; border-width: thin;}")),
      tags$style(HTML(".tabbable > .nav > li > a:hover {background-color: white; color:black; border-color: #212070; border-style: solid; border-width: thin;}"))
      
    ) #dashboard body end
  ), #dashboard page end
  
  #use java script for loading page icon
  useShinyjs(),
  #reference loading page icon 
  inlineCSS(appCSS)
  
) #fluid page end
}) #shiny UI end